### ISSUE TITLE
F3 3.6 and PHP7.1.2 splits session data

### ISSUE THREAD

**Issue by module0x90** [bcosca/fatfree-core#196]
Hi,

I have just replaced F3 3.5 with F3 3.6.
When I try to login (using DB based sessions), it just kicks me back out. Sessions data are created, more on that later.

I found https://groups.google.com/forum/#!topic/f3-framework/WfCJpW479Vw and applied the changes from 4f50cd0aa and 99b0dbdd5, but only for db/sql/session.php and session.php.

My session table looks like this:

```
*************************** 1. row ***************************
session_id: 0f3788b0be33d6ff0f0b49bf1c2d2ad7
      data: LastPageURL|s:0:"";CurrentPageURL|s:6:"/login";flash|a:2:{s:3:"msg";a:0:{}s:3:"key";N;}
        ip: XXXX
     agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
     stamp: 1487870281
      csrf:
*************************** 2. row ***************************
session_id: 1ebea216ad18349e9303cc532df8b481
      data: user|s:6:"tomtom";
        ip: XXXX
     agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
     stamp: 1487870281
      csrf:
*************************** 3. row ***************************
session_id: f6171995f7c94a0a554e38e288f83a9a
      data: LastPageURL|s:0:"";CurrentPageURL|s:1:"/";
        ip: XXXX
     agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
     stamp: 1487870281
      csrf:
```

It appears to me for every **$f3->set('SESSION.** the session id gets regenerated and it kinda splits up the vars into different sessions. The browser cookie I got is **0f3788b0be33d6ff0f0b49bf1c2d2ad7**, and that isn't referring **user: tomtom** - so no valid session and it requires to log me back in.
This was all working with 3.5 :-)

Cheers

Thomas

PS: I tried -dev, but oi! that changed too much.
